spring:
  application.name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: 'update'

server:
  port: 8080


jwt:
  secret: ${JWT_SECRET}