spring:
  application.name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: 'update'

  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
#                redirect-uri: http://localhost:8080/login/my-own-google

            github:
                client-id: ${GITHUB_CLIENT_ID}
                client-secret: ${GITHUB_CLIENT_SECRET}
server:
  port: 8080

client:
  redirect-url: http://localhost:5500

jwt:
  secret: ${JWT_SECRET}
