spring:
  application.name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

server:
  port: 8080
